[package]
name = "tallyhawk"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
colored = "3.0.0"
ignore = "0.4.23"
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
walkdir = "2.5.0"
